<?php

//Informações adicionais

echo "<p><center><br><br><font face=arial><font color=cc0000 size=5><b>FIM DO TESTE</b></font><br><br><br>
Muito bem, $nome! por responder o teste. Seu próximo passo é agendar uma entrevista, para que possamos dar-lhe o resultado pessoalmente,<b>sem nenhum custo</b>
<p>Obs: Este teste tem validade de no máximo 15 dias<br>
<p>Entre em contato conosco pelos fones: (11) 5071-9508 - (11) 4108-0799<p>";

echo "
<center>
<form method=post action=indica.php>
Escreva abaixo os motivos que te levaram a fazer este teste?<br>
<font size=1>
<textarea name=opiniao></textarea><br>
<input type=submit value='Avançar'>
</font></center>";


?>