<?php requere('parametros.php');?>

<TABLE cellSpacing=0 cellPadding=0 width=530 bgColor=f0f0f0 border=0 align=center>
<TBODY><TR><TD vAlign=center align=middle background="" height=100>
<FONT face=verdana color=gray size=1>
<p> Associa&ccedil;&atilde;o Brasileira de Dian&eacute;tica<br />
  Avenida Senador Casimiro da Rocha , 404 - Mirandópolis<br />
  Pr&oacute;ximo &agrave; Esta&ccedil;&atilde;o Pra&ccedil;a da &Aacute;rvore do Metr&ocirc;<br />
  S&atilde;o Paulo -SP - CEP: 04047-000<br />
<strong>Telefones: (11) 5071-9508 (11) 4108-0799</strong></p>
</FONT>
</TD></TR></TBODY></TABLE>
<br><font face=verdana size=1><center><?php echo date('Y'); ?> - Todos os Direitos Reservados a Associação Brasileira de Dianética</center></font>
<div class="footer">
<?php echo $empresa; ?>
</div>
</body>
</html>